### ISSUE TITLE
predict_step fails when input has more than one EPSG

### ISSUE THREAD

**Issue by brunosan** [Clay-foundation/model#120]
We should ensure datacubes only have one EPSG. 
Otherwise we [raise error](https://github.com/Clay-foundation/model/blob/0145e55bcf6bd3e9b19f5c07819a1398b6a22c35/src/model_clay.py#L898):
```python
  File "/home/brunosan/code/Clay/model/src/model_clay.py", line 920, in predict_step
    raise NotImplementedError(
NotImplementedError: More than 1 EPSG code detected: {32636, 32637}
```

Data cube created from branch `doc-prep`.

**Comment by yellowcap** [comment]
Closing as out of date, feel free to re open if appropriate.
