### ISSUE TITLE
Test partial input to Clay v0

### ISSUE THREAD

**Issue by yellowcap** [Clay-foundation/model#126]
After some discussions, we realized that there is a technical possiblity to run the Clay v0 model with partial inputs. We need to 

- [ ] Create an example notebook to show how that can be done
- [ ] Test the model with a benchmark that compares partial input (ideally one for Sentinel-2 and one for Sentinel-1) with full inputs.
- [ ] Document this.

**Comment by brunosan** [comment]
I suggest we make embeddings of a subset of the training data location, and compare. Probably both the usual average embeddings (at the patch level) and the smaller ones at the self-attention patch level. 

In the latter case, we would only have those corresponding to the groups we used as inputs, right?

So we compare:

| Input data |  Embedding | Case |
| ---| ---| -- | 
| All 13 bands | Normal ones (average at patch level `5kmx5km`) | The normal ones | 
| All 13 bands | self-attention patch groups `300mx300m` | Fine-level embeddings |
| Only RGB | Normal ones (average at patch level `5kmx5km`) | Restricted input, same output |
| Only RGB | self-attention patch groups | Fine embedding of band group `300mx300m`|
