### ISSUE TITLE
List and prioritize additional data sources for v1

### ISSUE THREAD

**Issue by yellowcap** [Clay-foundation/model#128]
To run the model on a more diverse universe of data, we need to list and prioritize new sources. An initial list is the following:

- [NAIP](https://registry.opendata.aws/naip/)
- [Open Aerial Map](https://openaerialmap.org/)
- [Landsat](https://aws.amazon.com/marketplace/pp/prodview-ivr4jeq6flk7u?sr=0-1&ref_=beagle&applicationId=AWSMPContessa#usage)
- [HLS](https://hls.gsfc.nasa.gov/)
- [CBERS](https://registry.opendata.aws/cbers/)
- [NZ High res imagery](https://registry.opendata.aws/nz-imagery/): comes with a static stac catalogue
- [Indiana state high res](https://registry.opendata.aws/in-imagery/)
- [Sentinel-3](https://registry.opendata.aws/sentinel-3/)
- [Sentinel-5](https://registry.opendata.aws/sentinel5p/)
- [Amazonia-1](https://registry.opendata.aws/amazonia/)
- [NOAA Emergency response imager](https://registry.opendata.aws/noaa-eri/)
- [New Jersey state high res](https://registry.opendata.aws/nj-imagery/)
- [Venus](https://registry.opendata.aws/venus-l2a-cogs/)
- [Modis](https://registry.opendata.aws/modis-astraea/)
- [Portuguese ortofotos 2018](https://snig.dgterritorio.gov.pt/rndg/srv/por/catalog.search#/metadata/d70dd232-aaee-4e6b-a804-5a0b70c537be), [2015](https://snig.dgterritorio.gov.pt/rndg/srv/por/catalog.search#/metadata/9d3e805d-bda5-4c3e-9879-6ebede3af6dc), [2021](https://snig.dgterritorio.gov.pt/rndg/srv/por/catalog.search#/metadata/d70dd232-aaee-4e6b-a804-5a0b70c537be), and 2023 coming up soon.
- [Swissimage 10cm](https://www.swisstopo.admin.ch/de/orthobilder-swissimage-10-cm)
- [Orthofotos Niedersachsen, Germany ](https://opengeodata.lgln.niedersachsen.de/#dop)
- [Orthofotos Thüringen, Germany](https://geoportal.thueringen.de/gdi-th/download-offene-geodaten/download-luftbilder-und-orthophotos)

## SAR
- [Radarsat-1](https://registry.opendata.aws/radarsat-1/)
- [Digital Earth Africa ALOS PALSAR, ALOS-2 PALSAR-2 and JERS-1](https://registry.opendata.aws/deafrica-alos-jers/)
- [Capella](https://registry.opendata.aws/capella_opendata/)
- [ARD Sentinel-1 for CONUS](https://registry.opendata.aws/sentinel-1-rtc-indigo/)

## For creating embeddings

- [ESA Worldcover composites](https://registry.opendata.aws/esa-worldcover-vito-composites/)
- [Sentinel-2 L2A 120m Mosaic](https://registry.opendata.aws/sentinel-s2-l2a-mosaic-120/)
- [Sentinel-2 Composites made by Germany](https://gdz.bkg.bund.de/index.php/default/wms-europamosaik-aus-sentinel-2-daten-wms-sen2europe.html)

**Comment by brunosan** [comment]
🎯 There are MANY layers and I'm truly excited to add them. Let's always ensure we do not use any data that is not fully open. Not even from automated Benchmarking. This way we do not carry over any resctriction for our models.

cc @lauracchen

**Comment by yellowcap** [comment]
Moving data into spreadsheet. 

[Link for editing (only Clay team)](https://docs.google.com/spreadsheets/d/1_C_nhIs2kJMq_AEdjMRUvLzoiJU0AeMl5F7S_DpfZ64/edit)

[Link for public download](https://docs.google.com/spreadsheets/d/e/2PACX-1vQAqRIV3uvfI8Pdve1gmBSM1JpJckQaN0i110aRo9qRe6YKj55glPQNu-GyVYTT4MASVrdBVJB8hh5D/pub?output=ods)

**Comment by fmacchiavello** [comment]
https://data.jrc.ec.europa.eu/dataset Joint Research Centre Data Catalogue I think could be helpful!

I know that European Commission’s Joint Research Centre global surface water dataset was useful for Skytruth's mask creation when doing amazon mining watch, to differentiate between mines and water, which often look very similar.

**Comment by yellowcap** [comment]
We can also potentially leverage imagery datasets that were designed for machine learning, but not necessarily for foundation models. The following reference contains an extensive list

https://captain-whu.github.io/DiRS/

**Comment by lauracchen** [comment]
Where did we land on which data sources would be incorporated?

@brunosan @danhammer @averycohn  Avery was bringing up the fact that there are potentially many oceans-related funders that we might want to pursue. Should we consider incorporating an initial attempt for covering oceans for model v1? Or would we just want to create a more oceans-focused use case that falls close to coastlines so that Clay's current geographic coverage with Sentinel would cover it? Or is this just too far out of the scope for now?

**Comment by yellowcap** [comment]
I would probably separate the two at first. For oceans, the data sources are quite different and the type of thing one would be looking for as well. We are planning to do the v1 pipeline in a way that should be adaptable to other contexts. So we could plan for an ocean model if we list ocean data sources. But for the v1 release I would not mix the two.

**Comment by ritwikvashistha** [comment]
Hi, I was experimenting with the model to get embeddings and was wondering whether Landsat 5 or 7 images can be used with the v1 to get the embeddings. They might not be part of the data module, but what if I have a geotiff for landsat images? Would that work?

**Comment by yellowcap** [comment]
Hi @ritwikvashistha yes that should be possible for v1. But v1 is still in development, we are targeting a release in May.

**Comment by brunosan** [comment]
> @lauracchen 
> ... there are potentially many oceans-related applications (and funders) that we might want to pursue. Should we consider incorporating an initial attempt for covering oceans for model v1? Or would we just want to create a more oceans-focused use case that falls close to coastlines so that Clay's current geographic coverage with Sentinel would cover it? Or is this just too far out of the scope for now?

Most data sources we use, open data, either don't map open ocean, or do it at very low resolution. On the other side, I would guess that the semantics of ocean surface are marginal additions to the land.

My take is that we can add all with minimal extra effort coastal data available on Sentinel/Landsat, and Modis at low res. I do not know to what degree this will be enough for many applications. I would suspect it can cover most of coastal applications.

Adding within scope open-ocean would be, unless @yellowcap corrects me, a level of effort beyond v1.

**Comment by brunosan** [comment]
For overview, this is the Sentinel coverage, that includes substatially all or part of the continental ocean shelves.

![image](https://github.com/Clay-foundation/model/assets/434029/a66a4b0d-6486-4df3-9765-ad617ad949d6)

**Comment by lauracchen** [comment]
@brunosan thanks! To be clear, does this mean that @yellowcap should update the v1 sampling to include more coastline / continental shelves?

**Comment by brunosan** [comment]
We have Sentinel-2, Landsat, and Naip as of today. Will ad NZ high res and Sentinel-1 next.
After that maybe Modis and Sentinel-3 and others.

**Comment by yellowcap** [comment]
The list of data we'll use for v1 is as follows, with chip counts from the [stacchip](https://github.com/Clay-foundation/stacchip) index as of today

Platform | Chip count
---------|-----------
naip|           20984171
linz|            3299006
sentinel-2-l2a| 18683945
landsat-c2l1|    5827333
landsat-c2l2-sr| 5790651
sentinel-1-rtc| 16133394
