### ISSUE TITLE
ERA 5 integration

### ISSUE THREAD

**Issue by yellowcap** [Clay-foundation/model#13]
Experiment with adding weather information from [ERA 5](https://www.ecmwf.int/en/forecasts/dataset/ecmwf-reanalysis-v5) for the input tiles as additional metadata that can help the model be better.

**Comment by weiji14** [comment]
The ERA5-PDS dataset on Planetary Computer only contains 12 surface or single level parameters (i.e. non of the 3D data variables at different atmospheric pressure levels), so out of the 7 variables listed in https://github.com/Clay-foundation/model/issues/13#issuecomment-1783156527, only 2m dewpoint temperature is available. [WeatherBench2](https://weatherbench2.readthedocs.io/en/latest/data-guide.html#era5) has one additional variable (`total_cloud_cover`) in Zarr, but if you want any other variables, they might need to be pulled from Copernicus, which can be quite a heavy lift.

Also note that these grids are typically at a spatial resolution of 0.25 arc degrees (~27.5km at the Equator), so super coarse resolution compared to Sentinel-2 at 10m (you mentioned 30m above, but I think you meant 30km). There are some downscaled datasets e.g. https://climate.copernicus.eu/high-resolution-climate-projections, but those are only for certain geographies and/or a limited set of data variables.

Maybe best to spell out 'Why' we want to add ERA5 to the Clay Foundation Model v0, or to put it another way, what is our motivation to combe Weather/Climate datasets with Earth Observation data (e.g. Sentinel-2)?

**Comment by yellowcap** [comment]
Due to the coarse spatial resolution of this data, it will not be incorporated as additional band into the datacube. We will evaluate the use of ERA 5 as additional context embedding, as an addition to the time and location embeddings.

**Comment by brunosan** [comment]
https://open-meteo.com/ offers an aPI for ERA5-Land, Global, at 0.1° (~11 km) resolution, hourly, from 1950 to present.
You must be on the 100$/month plan (which also provides the right license for us).

We be happy to pay for this, if it proves useful. So we can slate this for after v1

**Comment by yellowcap** [comment]
Lets park this for now and revisit when needed.
