### ISSUE TITLE
Update docs with benchmark tutorial

### ISSUE THREAD

**Issue by brunosan** [Clay-foundation/model#141]
After #117 has closed, I think we should update the documentation in two places, which I think are both small changes:

- [ ] Add a new model benchmark section, so in all future versions we compared how the scores are improving.  
- [ ] Add the code in the finetune section to help users apply finetuned for a random places with random labeled data, using the floods as the example.

**Comment by lauracchen** [comment]
Re-upping this @yellowcap - can we incorporate this in the next sprint?

**Comment by yellowcap** [comment]
Closing as out of date, feel free to re-open if appropriate.
