### ISSUE TITLE
Bbox, date, and cloud cover for patch level embeddings

### ISSUE THREAD

**Issue by yellowcap** [Clay-foundation/model#168]
To further enable patch level embeddings, two tasks:

1. Add functionality so that the `predict.py` routine outputs patch level embedding bounding box.
2. Track cloud coverage in each patch for quality filtering when using the embeddings
3. Include date stamp in the embedding database as well

This ticket is to track your request for patch level embeddings for bboxes  @danhammer

**Comment by lauracchen** [comment]
Hi @yellowcap do you have a sense of when this might be possible by? We're hoping to be able to fully work with patch-level embeddings and further explore their usefulness as soon as possible to inform next steps for our app development!

**Comment by lauracchen** [comment]
That's great to hear, thank you!

**Comment by lauracchen** [comment]
hi @yellowcap any update here or any roadblocks? Maybe @brunosan can help out if there's any blockers.

**Comment by brunosan** [comment]
not sure if already in scope, but also the option to not average the band groups.

**Comment by yellowcap** [comment]
We made good progress, I will review #172 today and hopefully we can merge that soon.

**Comment by lillythomas** [comment]
Yes @lauracchen I'm incorporating Daniel and Wei Ji's comments today, so #172 should be merged by Monday morning.

**Comment by lillythomas** [comment]
@lauracchen patch level bounding box, date and cloud cover information have been addressed in #172 and #184 respectively, both of which are merged into main now. The notebooks to demonstrate are `docs/tutorial_digital_earth_pacific_patch_level.ipynb` and `docs/patch_level_cloud_cover.ipynb`.

They use the Digital Earth Pacific data (#140) to focus the examples.

**Comment by lauracchen** [comment]
thank you so much!! @lillythomas

**Comment by yellowcap** [comment]
Closing this as done, let's reopen or make a new ticket for additional questions.
