### ISSUE TITLE
Sentinel 2 input spec and retrieval

### ISSUE THREAD

**Issue by lillythomas** [Clay-foundation/model#18]
### General specifications for v0
Initially, we've landed on selecting the 10-20 meter bands from Sentinel 2, plus the SLC band for tile-level cloud cover thresholding. 

The bands to be included:
- B2 (490 nm), 10 meter
- B3 (560 nm), 10 meter
- B4 (665 nm), 10 meter
- B8 (842 nm), 10 meter
- B5 (705 nm), 20 meter
- B6 (740 nm), 20 meter
- B7 (783 nm), 20 meter
- B8a (865 nm), 20 meter
- B11 (1610 nm), 20 meter
- B12 (2190 nm), 20 meter
- SLC (not for training)

We will use the L2A data product right now, but note that we discussed internally it may be worthwhile to explore a more applicable atmospheric correction method for water-related downstream tasks in future versions of the model.

### Retrieval

We will build on what @yellowcap started in https://github.com/Clay-foundation/model/pull/11, adjusting per the aforementioned specs.

**Comment by weiji14** [comment]
Closing as implemented in #27, feel free to comment further or reopen if we want to modify the specification further.
