### ISSUE TITLE
Release Clay v0.2

### ISSUE THREAD

**Issue by yellowcap** [Clay-foundation/model#190]
This model is currently training, this ticket can be completed once we are happy with the convergence.

- [ ] Publish the latest weights on huggingface 
- [ ] Make the documentation changes. I assume we can just leave legacy documentation on a folder with the version they pertain to.
- [ ] Make a release commit.

**Comment by brunosan** [comment]
Updated to add the documentation changes

**Comment by brunosan** [comment]
This is long done. Closing.
