### ISSUE TITLE
Resume trainning of  v0.2 with Bali data.

### ISSUE THREAD

**Issue by brunosan** [Clay-foundation/model#197]
To support the similarity search in our testbed of Bali, we are trying to improve the algorithm on #186 but I think it would help if we can take v0.2 and resume training only with Bali data for a few epochs. I believe this should increase the performace of similarity search, as a temporary solution to build the app UX/UI

Assigning to @yellowcap only to assign back to me once the v0.2 is released and I can pick it up to resume trainning.

cc @MaceGrim

**Comment by brunosan** [comment]
Actually we don’t really need to wait for 0.2 to finish, we could take any currently saved checkpoint from the EC2 right?

**Comment by yellowcap** [comment]
Yes that is correct @brunosan do you have the MGRS tiles identified that we would want to include? Any time range of interest?

**Comment by brunosan** [comment]
> Yes that is correct @brunosan do you have the MGRS tiles identified that we would want to include? Any time range of interest?

Latest but fine anytime say 5 years. We just want to  avoid locations that dissapeared from the set labels.
MGRSs are  `49LHL, 50LKR, 49MHM, 50MKS, 50MLS, 50LLR`.

<img width="355" alt="image" src="https://github.com/Clay-foundation/model/assets/434029/a856ceed-5255-4cbd-ae44-b104aa31a222">

Note: See https://github.com/Clay-foundation/office/issues/170#issuecomment-2018008564 for very partial coverage when running the standard datacube.py

![image](https://github.com/Clay-foundation/model/assets/434029/bd85e069-ad29-4230-a10a-a414c2ad8591)

**Comment by yellowcap** [comment]
Closing as out of date, feel free to re-open if appropriate.
