### ISSUE TITLE
Plots missing in tutorial notebooks

### ISSUE THREAD

**Issue by MaxLenormand** [Clay-foundation/model#199]
# Plots & outputs are missing from the tutorial notebooks

Here's an example from the first tutorial notebook, [clay-v0-reconstruction](https://clay-foundation.github.io/model/clay-v0-reconstruction.html):

![CleanShot 2024-03-27 at 12 12 11](https://github.com/Clay-foundation/model/assets/44133329/c57dc756-54e5-4c9e-9452-0da8b0cebc39)

I think this might be due to a cleaning of the notebook cell outputs before merging, as [the `.ipynb` has no outputs](https://github.com/Clay-foundation/model/blob/main/docs/clay-v0-reconstruction.ipynb)

**Comment by yellowcap** [comment]
Sorry to not getting back to you earlier on this @MaxLenormand . This particular notebook is deprecated, so I am closing the issue.
