### ISSUE TITLE
DEM specs and  retrieval

### ISSUE THREAD

**Issue by lillythomas** [Clay-foundation/model#20]
As a third input alongside Sentinel-1 and Sentinel-2, we think it would be broadly useful to include a DEM. To that end, we plan to use the 30 meter [Copernicus DEM GLO-30](https://planetarycomputer.microsoft.com/dataset/cop-dem-glo-30) from 2021, hosted on Planetary Computer.

**Comment by weiji14** [comment]
Closing as implemented in #27, feel free to comment further or reopen if we want to modify the data specification further.
