### ISSUE TITLE
Documentation versioning

### ISSUE THREAD

**Issue by brunosan** [Clay-foundation/model#208]
We currently have model v0, are trainning v0.2 and working on v1 models.
We should retain v0 documentation for those who will still use that model checkpoint, but add the new ones.

I propose to move documentation under folders with the version number. and add a banner on top of the legacy ones to link to the latest one.

e.g. 

```
https://clay-foundation.github.io/model/v0/
https://clay-foundation.github.io/model/v1/
...
```

**Comment by yellowcap** [comment]
We have moved the v0 docs into a "previous versions" section on the docs.
