### ISSUE TITLE
Full input file listing for Clay v0.2

### ISSUE THREAD

**Issue by brunosan** [Clay-foundation/model#209]
We need to release the full list of input images for the model v0.2. [Just like we have for v1](https://clay-foundation.github.io/model/specification.html#data-card). (Stanford transparency index suggests an explicit list of input files).

The `.txt` list is ~500Mb [9 733 925 lines], zipped its ~20Mb.

Right now is on this public Clay bucket with anonymous get policy. 

https://madewithclay-public.s3.amazonaws.com/Clay-model-v02-inputlist.zip

We might want a better way.

Leavign this Issue to remember to add to the documentation.

**Comment by yellowcap** [comment]
Closing as out of date, feel free to re open if appropriate.
