### ISSUE TITLE
Finetune application: Marine pollution dataset

### ISSUE THREAD

**Issue by brunosan** [Clay-foundation/model#215]
174 Sentinel-2 scenes captured between 2015-2022, with approximately 1.5M pixel-level annotations (_cl), confidence levels (_conf) and reports (_rep). These derive from 3 field-expert annotators.

https://marine-pollution.github.io/
<img width="1282" alt="image" src="https://github.com/Clay-foundation/model/assets/434029/e27d250b-b99e-4be2-9e07-fffd157c2cac">

License is open: Creative Commons Attribution 4.0 International

cc @danhammer @MaceGrim

**Comment by robmarkcole** [comment]
@brunosan just note these are L1C with atmospheric processing using ACOLITE

**Comment by yellowcap** [comment]
Closing this here @brunosan maybe transport this to a discussion or another place to track possible finetune applications?
