### ISSUE TITLE
Full coverage of smaller image size than chipped

### ISSUE THREAD

**Issue by brunosan** [Clay-foundation/model#224]
From @yellowcap, we will be able to input image sizes smaller than the chips we have (i.e. we crop the chip before feeding it into the model). This also means generating embeddings at smaller sizes thant the chip, which is important (#223).

I understand that we currently do random crop.

We need a method to fully generate all the subregions, so we in effect have full embedding coverage of the chip tiling at the desired size.

I believe this can be done after we start the training run.

**Comment by yellowcap** [comment]
Closing as out of date, feel free to re-open if appropriate.
