### ISSUE TITLE
Model v0 sensitivity test

### ISSUE THREAD

**Issue by lillythomas** [Clay-foundation/model#23]
We had a discussion around focusing a small initial training experiment to a curated set of geographies with a known history of some anticipated downstream detection problem (e.g. for floods or landslides). Reason being, we'd like to test the sensitivity of a smaller, geographically-curated, event-focused model for a specific downstream task before testing on a larger, global, event-agnostic model. Ideally, we'd have a few AOIs selected for training and select a test site for the downstream task.

**Comment by yellowcap** [comment]
Closing in favor of https://github.com/Clay-foundation/model/issues/117
