### ISSUE TITLE
Generate v1 Embeddings

### ISSUE THREAD

**Issue by brunosan** [Clay-foundation/model#235]
We need to generate embeddings, like on v0.1, on all the training set.

Since we are currently doing random cropping on the training set on loading, we also need to implement full coverage. 

This is especially important since we now have different embeddings for each instrument. Ideally all embeddings are instrument agnostic, but we don't know yet, so it's important to maximize the overlap to check for that.

Related #207.

**Comment by lauracchen** [comment]
When can we expect the script used to generate the v1 embeddings to be created/updated? The app team is hoping they can begin to integrate this ASAP to see if they can get v1 embeddings into the app in time for SatSummit.

cc @antymoro @lukaszknasiecki

**Comment by yellowcap** [comment]
We generated embeddings for multiple regions and have an embedding builder. So running the embeddings on the training set might not be so useful anymore.
