### ISSUE TITLE
v1 Release

### ISSUE THREAD

**Issue by brunosan** [Clay-foundation/model#248]
- [x] Basic documentation to train/inference
- [x] Model card
- [x] Data card.
- [x] GH release commit.
- [x] Deploy buttons working (the ones on the main readme).
- [x] Model checkpoints on HF.

related #208

**Comment by lauracchen** [comment]
hi @srmsoumya just logging here from Slack - can you do super quick writeups of your results from experimenting with clay for 
classification and segmentation downstream tasks, either as discussions on GH or blog posts/something similar? I'm also happy to help polish it up if you want to get the content bullets down, but doesn't have to be super polished either way

cc @brunosan

**Comment by srmsoumya** [comment]
@lauracchen I have added the details on experiments here: https://github.com/Clay-foundation/model/discussions/269

**Comment by yellowcap** [comment]
Almost there!
https://github.com/Clay-foundation/model/pull/273

I would vote for externalizing the embeddings publication into a separate issue. We should discuss how to publish these best.

**Comment by yellowcap** [comment]
🍾 All items done! 🕺🏽
