### ISSUE TITLE
Code Sprint: Finish Regression, Classification, Object Detection and Segmentation

### ISSUE THREAD

**Issue by brunosan** [Clay-foundation/model#275]
Largely speaking, there are these types way one could apply the model:

* Similarity at embedding level:
    * Code: ✅ Inference code and no-code Build/Explore.
    * Docs:  ✅ Both Documentation and Notebook 
* Regression:
    * Code: 🚧 Pending
    * Docs: 🚧 Pending
* Classification:
    * Code: ✅ https://github.com/Clay-foundation/model/pull/270
    * Docs: 🚧 Pending, some on #269 
* Segmentation:
    * Code: ✅ https://github.com/Clay-foundation/model/tree/main/finetune/segment
    * Docs: 🚧  Pending, some on #269 
* Object Detection:
    * Code: 🚧 Pending
    * Docs: 🚧 Pending
* Change Detection:
    * Code: 🚧 Pending
    * Docs: 🚧 Pending, partly done with the Portugal notebook.

@yellowcap Can you please scope the sprint around these?

**Comment by brunosan** [comment]
Regression, Classification and segmentation shipped. 

Object detection and Change detection delayed for now.

**Comment by dokterbob** [comment]
Object Detection wennnn? ;)

**Comment by robmarkcole** [comment]
Any estimates on Object detection and Change detection?

**Comment by yellowcap** [comment]
@robmarkcole this is put on hold for now, we do not have visibility on when we can get back to object and change detection.
