### ISSUE TITLE
Develop geographic sampling strategy based on Worldcover

### ISSUE THREAD

**Issue by yellowcap** [Clay-foundation/model#28]
To have balanced data we probably need to oversample certain land cover types such as urban areas and wetlands. We will use a simplified version of the [Worldcover](https://esa-worldcover.org/en) dataset for this sampling effort.

Deliverables:

- [x] A script for doing sampling based on landcover classes
- [x] A list of locations / scenes to process for the initial data collection

**Comment by brunosan** [comment]
As much as possible, please try to tweak this to add other sampling sources.

If we only sample to have all and roughly equal classes of land cover, we are teaching the model that that is the important variance to pay attention. This is not wrong, but I worry we will underindex the semantics that many applications need to learn about nature (besides land cover) and people. I.e. if possible sample also from:

For nature:
* [Biodiversity Intactness](https://planetarycomputer.microsoft.com/dataset/io-biodiversity)
* [Global Biodiversity Information Facility (GBIF)](https://planetarycomputer.microsoft.com/dataset/gbif) 

For people and human assets:
* [Population Density](https://sedac.ciesin.columbia.edu/data/set/gpw-v4-population-density-rev11/data-download)
* A derived dataset with number of [Building Footprints](https://planetarycomputer.microsoft.com/dataset/ms-buildings)
