### ISSUE TITLE
Issues with exporting the model using torch.jit.script

### ISSUE THREAD

**Issue by szymonzmyslony** [Clay-foundation/model#280]
Hi,
I am trying to export the encoder part of the model so that I can run using TorchServe. I am trying to run: 
```import torch
from src.model import ClayMAEModule
METADATA_PATH = "./configs/metadata.yaml"
def get_model_from_ckpt(ckpt):
    model = ClayMAEModule.load_from_checkpoint(
        ckpt, metadata_path=METADATA_PATH, shuffle=False, mask_ratio=0.0
    )
    model.eval()
    encoder = model.model.encoder
    return encoder
model = get_model_from_ckpt('./clay-v1-base.ckpt')
script_module = torch.jit.script(model)
script_module.save('clay_encoder.pt')
```
but am getting some type errors associated with F.multi_head_attention_forward type mismatch (int vs float expected). Have you had similar problems ? Can you point me in the right direction on how to best serve it ?

**Comment by weiji14** [comment]
Hmm, I did a quick search, and wondering if it's related to https://github.com/pytorch/pytorch/issues/20722? Could you let us know what version of Pytorch you are running this on?

Ping @srmsoumya also, who was trying to get torchscript to work last month. I recall there were some issues with einsum not working with torchscript for some layers in the neural network, so maybe he has some ideas on how to help.

**Comment by szymonzmyslony** [comment]
I'm running ` pytorch~=2.1.0  # [mac silicon]`

**Comment by srmsoumya** [comment]
@szymonzmyslony There are a few issues we need to address on the model side to make it scriptable. Specifically, if/else blocks in the forward call, dictionaries for dataloaders, einops operations, tuples as models, and the new MHA attention mechanism all throw errors when we try to torch.jit.script the model. We will aim to include these enhancements in the next release to make it fully scriptable.

**Comment by szymonzmyslony** [comment]
Understood ! Thanks a lot for the reply, how can I help to make this happen ?
Is there a way to deploy the model today without using Lightning ?

**Comment by srmsoumya** [comment]
Thanks you @szymonzmyslony 

Yes, we can load the pre-trained weights without using lightning, [here is an example](https://github.com/Clay-foundation/model/blob/main/finetune/classify/factory.py) on how to do that for classification downstream task.
