### ISSUE TITLE
Training run for Clay v1.5

### ISSUE THREAD

**Issue by yellowcap** [Clay-foundation/model#283]
Ideas to add are
- Train a larger model version
- Use SAM as teacher model
- Add Satellogic data to reduce bias on high res training

**Comment by rbavery** [comment]
https://x.com/osanseviero/status/1807679660328620099

^ Possible funding source for model distillation work.

**Comment by lauracchen** [comment]
Ok @brunosan could you help determine a priority list here? The other thing I'd love to see is if we can add MODIS data, as long as the architecture won't need to change

**Comment by brunosan** [comment]
Update: MODIS has been just added. #311
Nor adding Satellogic to the foundational training due to license (we understand clay would then need to carry a "cc-by satellogic" on the trained model). 
We are now securing compute block

**Comment by rbavery** [comment]
Curious why CC-By is a blocker? this article indicates that the model can be used, even commercially, with attribution. https://satellogic.com/2024/05/01/satellogic-open-source-release-a-large-dataset-of-high-resolution-imagery-for-ai-model-training/

For any high res dataset sourced from a commercial provider, I expect they will at least want this kind of attribution. Having a model that understands submeter resolutions in addition to coarser resolution public imagery would be very valuable.

**Comment by brunosan** [comment]
> Curious why CC-By is a blocker? 

This is for foundational training. If we train with data that requires attribution, we understand it means that the attributions carries over to the trained model, and all users of Clay need also to attribute it, which would bring higher friction. E.g. If Planet incorporates Clay on the pipeline, they might need to attribute Satellogic when using Clay.

This of course does not prevent us, or anyone, to make a finetuned version of Clay with Satellogic, or Maxar or Planet data. That version would carry the licenses of the data used.

fwiw, Clay is trained with NAIP and LINZ, which are both well under 1 meter. (32% of the 70 million chips)

PS: AFAIK it is not legally settled if the license of each training data carries over to the trained model. In LLMs the practice seems not to, but we choose to take the safer position and only use fully open data.

**Comment by srmsoumya** [comment]
Update: We are conducting another model run for CLAY with the following updates:

- Added MODIS to the list of sensors. #311 
- Implemented [MRL](https://arxiv.org/abs/2205.13147) on CLAY embeddings.
- Introduced [SAM as the new teacher model](https://arxiv.org/abs/2304.02643).
- Using Fused Transformers as the Encoder/Decoder backbone.
- Switching to Fused Adam and [8-bit Adam](https://huggingface.co/docs/bitsandbytes/main/en/optimizers) as optimizers.
- Reduced the decoder size for MAE.
- Randomly dropping latitude, longitude, and time information.
- Randomly dropping some or all channels.
- Converting Sentinel-1 data from raw values to dB scale.

We are running several experiments with these changes, and based on the results, the successful adjustments will be included in the new model run. Keep track of the changes in [dev branch](https://github.com/Clay-foundation/model/tree/dev).

**Comment by brunosan** [comment]
Update:
Clay v1.5 - Running a 20 node G6 g6.48xlarge cluster, or 160 L4 GPUs at 100% power. It will take ~8 hours an epoch, with the expanded corpus with MODIS. Clay v1 was 50h/epoch without MODIS. See above for changes implemented, plus a large Transformer size, of ~500 Million params, instead of ~200M.

![Screenshot 2024-08-23 at 14 24 55](https://github.com/user-attachments/assets/e0b020b5-a65c-4531-8795-55bae9698971)

**Comment by brunosan** [comment]
6 epochs. No sign of plateauing.

![screenshot_2024-08-25_at_10.48.18_pm.png](https://github.com/user-attachments/assets/1b6f1d17-ab6c-4c35-8987-58e12d9c7d01)

**Comment by brunosan** [comment]
![image-1.png](https://github.com/user-attachments/assets/968b2f98-2723-4ff4-a97c-fa2e62c068ae)

Naip reconstruction

**Comment by print-sid8** [comment]
Hi guys, would be glad to hear of any updates on this. Thanks

**Comment by brunosan** [comment]
Still training. Will stop soon and do the embeddings run for the world #277 


Very promissing lossess:
![Screenshot 2024-10-01 at 12 09 32](https://github.com/user-attachments/assets/362d2326-e52c-432c-a266-51da12211b1f)

and reconstructions:
![image](https://github.com/user-attachments/assets/ecfc2937-8ef9-463b-9f4c-be33c653dac2)


anything else in particular you would like to know @print-sid8 ?

**Comment by joshuacortez** [comment]
Hi @brunosan , I've been following the Clay project and I've been using Clay v1.0 in my current project. Amazing work from the team!

I'm curious about the release of Clay v1.5, should we expect the weights to get uploaded to HuggingFace anytime soon? Thanks!

**Comment by joshuacortez** [comment]
Got this, thanks for the update! Looking forward to the link

**Comment by brunosan** [comment]
Clay v1.5 is already on HF.
https://huggingface.co/made-with-clay/Clay/blob/main/clay_v1.5.ckpt
Documentation is still pending and the model will be officially released net week, but feel free to use it, branch is https://github.com/Clay-foundation/model/tree/dev

Closing here as the run is done.
