### ISSUE TITLE
Assess how to add Satellogic data to Clay trainign pipeline

### ISSUE THREAD

**Issue by yellowcap** [Clay-foundation/model#284]
This data does not come with STAC catalogues, so we have to inspect how much work it is to add it.

**Comment by lauracchen** [comment]
This seems like a great idea to also help with higher resolution inference, which many partners are interested in. Should we do this before the global runs? @brunosan #277

**Comment by yellowcap** [comment]
The cc-by license is a blocker so we are not using satellogic for now https://github.com/Clay-foundation/model/issues/283#issuecomment-2257489617
