### ISSUE TITLE
Missing segment.py and classify.py for model finetune

### ISSUE THREAD

**Issue by dokterbob** [Clay-foundation/model#299]
As referred to from README's:
- https://github.com/Clay-foundation/model/blob/main/finetune/segment/README.md?plain=1#L115
- https://github.com/Clay-foundation/model/blob/main/finetune/classify/README.md?plain=1#L99

Maybe the README's are wrong, and there's another way to train?

I don't know, never did PyTorch Lightning -- but I guess we should have a file with `L.Train()` somewhere?

P.S. ❤️ ❤️ ❤️ your work. We want to build upon it with https://treescape.app

**Comment by dokterbob** [comment]
Ref: #275

**Comment by yellowcap** [comment]
@dokterbob these files actually sit at the root of the model repo. This is to be able to run them straight off the model repo folder. But your question makes me think that we should reconsider this and maybe move them in to their respective finetune folders.

@srmsoumya let's think about this when we integrate these examples into the docs better.

https://github.com/Clay-foundation/model/blob/main/segment.py
https://github.com/Clay-foundation/model/blob/main/classify.py
https://github.com/Clay-foundation/model/blob/main/regression.py

Thanks for the kind words @dokterbob ! Great to see enthusiasm around our model!

**Comment by dokterbob** [comment]
@yellowcap Thanks for getting back. How silly, I'd swore I'd looked at that. I see they were added some weeks ago, perhaps I was looking before that? *confusedface*

Reviewing the contents though, they're just wrappers with hard dependencies on their respective fine-tuning module. From that perspective, yes, they belong in those sections.

If and when I start giving this a test drive I can fire a PR.

Then again, all they do is refer to a data module and the model. Perhaps we don't need different entry points for that, rather just a `--datamodule` and ``--model` argument on the `trainer.py` entry point. You'd specify the import path and the script does a dynamic import, e.g. `finetune.segment.chesapeake_datamodule.ChesapeakeDataModule`. 

Actually, I believe that the Pytorch Lightning CLI already does that. Less code means less maintenance on code and docs for you! ;)

That would make it fully generalisable to actual use cases -- where people will always want to train on their own data (I do...!).
