### ISSUE TITLE
v0 Embeddings

### ISSUE THREAD

**Issue by brunosan** [Clay-foundation/model#3]
Aiming for a set of geographically anchored files that fully cover Earth land and coast, where each one contains a vector with a mathematical representation of the semantics on that location, subject to be fine tuned with higher resolution, or finer set of semantics.

For v0 we can restrict the embeddings to a certain RoI, a certain time window, a certain vector length.

**Comment by brunosan** [comment]
Updated to re-scope.

**Comment by yellowcap** [comment]
We will focus on three type of embedding initially

- Instrument (bands). Model should not expect all bands.
- Time with time of day, year, month.
- Location with lat/lon plus extent or resolution. A promising option is [Spherical harmonics](https://arxiv.org/abs/2310.06743).

Refs

https://github.com/Clay-foundation/model/issues/22
https://github.com/Clay-foundation/model/issues/12

**Comment by yellowcap** [comment]
Closing this with a reference to the [new issue for Sprint 2](https://github.com/Clay-foundation/office/issues/34).

**Comment by brunosan** [comment]
Per our call, DevSeed team will create and "embeddings factory" script to run ideally as CI on release versions. 

The locations and times to generate will be defined {by Ode's team}, but for v0 ideally not too large. 

It also seems that creating embeddings for (some of) the training dataset is a small incremental effort since that data is already prepared.

**Comment by brunosan** [comment]
v0 documentation #118 includes how to create embeddings for any location and time.
