### ISSUE TITLE
Optional inputs / generative tasks

### ISSUE THREAD

**Issue by brunosan** [Clay-foundation/model#30]
This is low priority for v0, but I think it is worth assessing level of effort.

Would it make sense to make all inputs optional?

I understand we currently provide as an input everything, always: the image (with masked out patches), location, time, instrument, ...

I want to understand if we can drop some of those inputs, specifically the image one. These are some applications where this can unlock a lot of value:

- **If we don't provide an image** it would be extremely valuable to make a finetuned application to generate the expected image. In essence creating a "semantically compressed" model of Earth. To the degree that this works, it could provide e.g. cloudfree RGB images, synthetic SAR, extremely fast approximation of a basemap in device...
- **If we don't provide a location** we can still try to infer semantics. This is useful to leverage images without locations information. We can also finetune to predict locations, which can help locate, or fix locations of images.

I can see implementing this making the MAE 100% of the image some of the times, and/or masking other inputs (and adding a flag). I expect the loses much greater in those cases, but it can hopefully force the model to learn absolute anchors in the model, instead on relative to the available patches on the image.

Does this make sense?

**Comment by yellowcap** [comment]
That makes sense for a foundation model, it should be able to handle many different kinds of inputs and missing data etc. I think that also relates to time series of imagery.

- We could envision a system that has "slots" for many different satellites systems and data sources, but not expecting all of them at once.
- When going into time series data, we will have missing time steps as well, or "alternating" data providers that are not simultaneous but could be input in sequence.

This can be integrated in the masking strategy, a great example for a masking strategy that takes these things into account is [NASA Havest's Presto model](https://github.com/nasaharvest/presto).

I agree though that for v0 its not the main focus.
