### ISSUE TITLE
Downstream application:  coconut palm plantation

### ISSUE THREAD

**Issue by brunosan** [Clay-foundation/model#32]
Tagging here a possible finetune application of Clay, or downstream benchmark.

Microsoft AI for Earth provided funding for [this project](https://essd.copernicus.org/articles/15/3991/2023/essd-15-3991-2023.html) to use a Unet on Sentinel-1 and Sentinel-2, trained on 10,200 labels of coconut palm plantations, and achieves a precision of `79.21%` and recall of `71.51%`, for closed-canopy palms only.

Labels dataset are available [here](https://zenodo.org/records/8128183).

Paper author is @adriadescals.

**Comment by yellowcap** [comment]
Closing as out of date, feel free to re open if appropriate.
