### ISSUE TITLE
Downstream Application: Compare to SAM

### ISSUE THREAD

**Issue by brunosan** [Clay-foundation/model#33]
This is a great overview [applying SAM for Geospatial](https://www.sciencedirect.com/science/article/pii/S1569843223003643#sec4). It would be a great benchmark to compare our segmentation to SAM's, specially since SAM seems to fail with resolutions below 60cm (it wasn't trained on anything similar).

**Comment by yellowcap** [comment]
We are considering using SAM as the teacher network in future training runs. Closing as out of date, feel free to re open if appropriate.
