### ISSUE TITLE
Needs for CTrees Collaboration

### ISSUE THREAD

**Issue by MaceGrim** [Clay-foundation/model#58]
I want to make sure that we can hit the ground running with CTrees when the embeddings come online. It takes them a certain period of time to generate their data for a ROI.

Do we know where our first set of embeddings are being generated?

When we know the location/timeframe, we can give that to them and they can work on generating their data in parallel.

**Comment by brunosan** [comment]
Yes. 
the agreement was to start by creating embeddings for all the 970M chips used for training. See "Sampling" section here https://github.com/Clay-foundation/office/issues/34#issuecomment-1825963858 

If you need specific regions to be added to the "embeddings factory", please ping @yellowcap and we scope how to deal with that. DevSeed is creating the script to make these, https://github.com/Clay-foundation/model/pull/56

**Comment by brunosan** [comment]
v0 Documentation includes how to create embeddings for any location and time.
