### ISSUE TITLE
Timestamp in TIF metadata for data pipeline output

### ISSUE THREAD

**Issue by yellowcap** [Clay-foundation/model#70]
To facilitate its use and persist beyond the file name.

See also https://github.com/Clay-foundation/model/pull/54#pullrequestreview-1761464883

**Comment by weiji14** [comment]
Looking at whether there's a standard to encode the acquisition datetime in a GeoTIFF at https://gdal.org/drivers/raster/gtiff.html#metadata. A couple of options:

- [`ACQUISITIONDATETIME`](https://gdal.org/user/raster_data_model.html#imagery-domain-remote-sensing)
- [`TIFFTAG_DATETIME`](https://gdal.org/user/raster_data_model.html#metadata)

Both of these expect a datetime (with year, month, date, hour, minute second) though, but currently we are only storing YYYY-MM-DD. Which one should we go for?

**Comment by yellowcap** [comment]
> Looking at whether there's a standard to encode the acquisition datetime in a GeoTIFF at https://gdal.org/drivers/raster/gtiff.html#metadata. A couple of options:

Sorry only saw this now. Went with simple `date`. But can adapt in v3.

**Comment by yellowcap** [comment]
Looking into this, changing this tag needs refactoring also in the data-pipeline, finding the simple "date" tag and replace it with the choice of use [ACQUISITIONDATETIME](https://gdal.org/user/raster_data_model.html#imagery-domain-remote-sensing) or [TIFFTAG_DATETIME](https://gdal.org/user/raster_data_model.html#metadata).

**Comment by yellowcap** [comment]
This is in the[ `date` tag in the tiff files for v0.1 and v0.2](https://github.com/Clay-foundation/model/blob/8f1d8692794e54c27b3a9ca9f6f59c8746819fa9/src/datamodule.py#L63), and will move into the STAC Item / stacchip index for v1.
