### ISSUE TITLE
benchmark datasets

### ISSUE THREAD

**Issue by brunosan** [Clay-foundation/model#82]
For the linear probes, we are using c2smsfloods (#75).
I'd like us to consider also other Sentinel-derived products:

- [ESA's WorldCereal](https://esa-worldcereal.org/en/about/worldcereal-products)
- [METER-ML](https://stanfordmlgroup.github.io/projects/meter-ml/)
- Ctrees ( @fmacchiavello to clarify here if we can download an open-data global output).

**Comment by yellowcap** [comment]
Closing as out of date, feel free to re open if appropriate.
