### ISSUE TITLE
Check for undersampling of certain geographic regions due to cloud cover filters

### ISSUE THREAD

**Issue by weiji14** [Clay-foundation/model#93]
In #28 and #80, we've developed a geographic sampling scheme based on WorldCover that is supposed to sample a diverse set of regions based on landcover types.

However, in #60/#68, we've applied a NoData filter that removes some of those sampled regions. We'll need to double check if those filters are undersampling certain geographic regions that have high cloud cover, or areas where high surface reflectance can lead to false positive cloud cover values (e.g. over polar regions).

For example, we should have 40+ MGRS tiles over Greenland with the sampling procedure from #81:

![image](https://github.com/Clay-foundation/model/assets/23487320/d1f09b72-e518-424d-945a-ef70895c0dac)

But I looked at the s3 bucket, searching over 20X-26X, 21W-26W, 22V-24V, and couldn't find a single tile, even in the coastal areas that are not pure white!

So we'll need to check if there are certain data gaps, and potentially increase the cloud cover threshold or something.

**Comment by yellowcap** [comment]
We addressed this by using the least cloudy image for each season in an area. This increases the chances of getting enough imagery in each region. But the bias might still be there, since in very cloudy areas even that approach might lower the number of samples.

We can revisit in a later stage.
